# term-project docker compose
version: "3"
services:
  redis:
    image: redis
    ports:
    - '6379'

  rabbitmq:
    image: rabbitmq
    ports:
    - '5672'

  base:
    build: base
    image: "local/term-project-base"

  controller:
    image: "term-project-controller"
    ports:
      - '5000'
    depends_on:
      - base
      - rabbitmq
      - redis

  scanner:
    image: "term-project-scanner"
    depends_on:
      - base
      - rabbitmq
      - redis

  spider:
    image: "term-project-spider"
    depends_on:
      - base
      - rabbitmq
      - redis
