# term-project docker compose
version: "3"

services:
  redis:
    image: redis
    ports:
    - '6379'

  rabbitmq:
    image: rabbitmq
    ports:
    - '5672'

  base:
    build: base
    image: 'local/term-project-base'

  controller:
    build: controller
    image: 'term-project-controller'
    ports:
      - '5000'
    depends_on:
      - base
      - rabbitmq
      - redis

  scanner:
    build: scanner
    image: 'term-project-scanner'
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: '/usr/src/app/term-project.json'
    depends_on:
      - base
      - rabbitmq
      - redis

  spider:
    build: spider
    image: 'term-project-spider'
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: '/usr/src/app/term-project.json'
    depends_on:
      - base
      - rabbitmq
      - redis
